FROM python:3.10

WORKDIR /app

COPY config/requirements.txt .
RUN pip install --no-cache-dir --upgrade -r requirements.txt

COPY app .
CMD ["uvicorn", "src.main.app:app", "--host", "0.0.0.0", "--port", "8000"]