services:
  mongodb:
    container_name: todo-api-mongo
    image: mongo

  api:
    container_name: todo-api
    build:
      context: ..
      dockerfile: docker/Dockerfile.app.dev
    depends_on:
      - mongodb
    links:
      - mongodb
    ports:
      - 8000:8000
    env_file:
      - ../config/app.env
